### PR TITLE
ci: os update

### PR DESCRIPTION
**Pull request by crazy-max**

### CODE REVIEW

**Comment by crazy-max** [comment]
Linker issue with Ubuntu 24.04: https://github.com/tonistiigi/xx/actions/runs/7289833591/job/19865313633#step:5:1259

```
#81 455.4 #   /usr/lib/go-1.21/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=IGuRvBhAU54HTMlye0Xd/8xiVMZZniOnwxuvRzyaU/0wGn0ncdtLbr0aZyGuS5/IGuRvBhAU54HTMlye0Xd -extld=aarch64-linux-gnu-clang $WORK/b001/_pkg_.a
#81 455.4 #   # command-line-arguments
#81 455.4 #   /usr/lib/go-1.21/pkg/tool/linux_amd64/link: running aarch64-linux-gnu-clang failed: exit status 1
#81 455.4 #   /usr/bin/ld: unrecognised emulation mode: aarch64linux
#81 455.4 #   Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386pep i386pe
#81 455.4 #   aarch64-linux-gnu-clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tonistiigi** [comment]
To unblock this we need to see `-v` and if this is coming from lld or binutils.

**Review by tonistiigi — COMMENTED** [review]
Add `debian:trixie` as well.

**Review by tonistiigi — APPROVED** [review]
With the latest patches this should be green (except buster-backports that we maybe should start removing soon).

It does look that trixie sometimes has package sync errors (like we have seen in sid). We might need to set "allow-failure: true" if this persists.

**Pull request merged**
