### PR TITLE
enable experimental riscv64 support

### PR DESCRIPTION
**Pull request by tonistiigi**
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
Bad signature errors for some packages :(

```
#32 87.29 not ok 29 riscv64-hellocgo
#32 87.29 # (from function `xxadd' in file test_helper.bash, line 21,
#32 87.29 #  from function `testHelloCGO' in file test-go.bats, line 169,
#32 87.29 #  in test file test-go.bats, line 209)
#32 87.29 #   `testHelloCGO' failed with status 5
#32 87.29 # fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/riscv64/APKINDEX.tar.gz
#32 87.29 # (1/1) Installing alpine-keys (2.3-r1)
#32 87.29 # OK: 0 MiB in 1 packages
#32 87.29 # + apk  --root /riscv64-alpine-linux-musl add musl-dev gcc
#32 87.30 # fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/riscv64/APKINDEX.tar.gz
#32 87.30 # (1/13) Installing musl (1.2.2-r3)
#32 87.30 # (2/13) Installing zlib (1.2.11-r3)
#32 87.30 # (3/13) Installing binutils (2.35.2-r2)
#32 87.30 # (4/13) Installing libgomp (10.3.1_git20210625-r0)
#32 87.30 # ERROR: libgomp-10.3.1_git20210625-r0: BAD signature
#32 87.30 # (5/13) Installing libatomic (10.3.1_git20210625-r0)
#32 87.30 # ERROR: libatomic-10.3.1_git20210625-r0: BAD signature
#32 87.30 # (6/13) Installing libgcc (10.3.1_git20210625-r0)
#32 87.30 # ERROR: libgcc-10.3.1_git20210625-r0: BAD signature
#32 87.30 # (7/13) Installing gmp (6.2.1-r0)
#32 87.30 # (8/13) Installing isl22 (0.22-r0)
#32 87.30 # (9/13) Installing mpfr4 (4.1.0-r0)
#32 87.30 # (10/13) Installing mpc1 (1.2.1-r0)
#32 87.30 # (11/13) Installing libstdc++ (10.3.1_git20210625-r0)
#32 87.30 # ERROR: libstdc++-10.3.1_git20210625-r0: BAD signature
#32 87.30 # (12/13) Installing gcc (10.3.1_git20210625-r0)
#32 87.30 # ERROR: gcc-10.3.1_git20210625-r0: BAD signature
#32 87.30 # (13/13) Installing musl-dev (1.2.2-r3)
#32 87.30 # 5 errors; 28 MiB in 9 packages
```

@ncopa Is there a place to leave feedback on the new riscv developments or is it too early atm. Btw, I also made https://github.com/tonistiigi/dockerfile-alpine

**Review by crazy-max — APPROVED** [review]

**Comment by crazy-max** [comment]
Oh community packages available gret!

**Comment by ncopa** [comment]
> Bad signature errors for some packages :(
> 
> ```
> #32 87.29 not ok 29 riscv64-hellocgo
> #32 87.29 # (from function `xxadd' in file test_helper.bash, line 21,
> #32 87.29 #  from function `testHelloCGO' in file test-go.bats, line 169,
> #32 87.29 #  in test file test-go.bats, line 209)
> #32 87.29 #   `testHelloCGO' failed with status 5
> #32 87.29 # fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/riscv64/APKINDEX.tar.gz
> #32 87.29 # (1/1) Installing alpine-keys (2.3-r1)
> #32 87.29 # OK: 0 MiB in 1 packages
> #32 87.29 # + apk  --root /riscv64-alpine-linux-musl add musl-dev gcc
> #32 87.30 # fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/riscv64/APKINDEX.tar.gz
> #32 87.30 # (1/13) Installing musl (1.2.2-r3)
> #32 87.30 # (2/13) Installing zlib (1.2.11-r3)
> #32 87.30 # (3/13) Installing binutils (2.35.2-r2)
> #32 87.30 # (4/13) Installing libgomp (10.3.1_git20210625-r0)
> #32 87.30 # ERROR: libgomp-10.3.1_git20210625-r0: BAD signature
> #32 87.30 # (5/13) Installing libatomic (10.3.1_git20210625-r0)
> #32 87.30 # ERROR: libatomic-10.3.1_git20210625-r0: BAD signature
> #32 87.30 # (6/13) Installing libgcc (10.3.1_git20210625-r0)
> #32 87.30 # ERROR: libgcc-10.3.1_git20210625-r0: BAD signature
> #32 87.30 # (7/13) Installing gmp (6.2.1-r0)
> #32 87.30 # (8/13) Installing isl22 (0.22-r0)
> #32 87.30 # (9/13) Installing mpfr4 (4.1.0-r0)
> #32 87.30 # (10/13) Installing mpc1 (1.2.1-r0)
> #32 87.30 # (11/13) Installing libstdc++ (10.3.1_git20210625-r0)
> #32 87.30 # ERROR: libstdc++-10.3.1_git20210625-r0: BAD signature
> #32 87.30 # (12/13) Installing gcc (10.3.1_git20210625-r0)
> #32 87.30 # ERROR: gcc-10.3.1_git20210625-r0: BAD signature
> #32 87.30 # (13/13) Installing musl-dev (1.2.2-r3)
> #32 87.30 # 5 errors; 28 MiB in 9 packages
> ```
> 
> @ncopa Is there a place to leave feedback on the new riscv developments or is it too early atm. Btw, I also made https://github.com/tonistiigi/dockerfile-alpine

I don't think its too early to give feedback on riscv development. Not sure where the proper location for this specific error though. I guess you can create an issue in https://gitlab.alpinelinux.org/alpine/aports/-/issues and someone will route it to the proper place.

You can also join #alpine-devel on OFTC IRC network. Seems like there are lots of interest in riscv recently.

**Comment by crazy-max** [comment]
@ncopa Think this "was" linked to https://gitlab.alpinelinux.org/alpine/aports/-/issues/12167#note_165240

**Comment by clandmeter** [comment]
As i mention in the linked issue, gcc has been rebuild and cdn has cached older pkgs.
I have already purged the packages from the cdn, so it should work now.

**Pull request merged**
