### PR TITLE
ci: update alpine to 3.21

### PR DESCRIPTION
**Pull request by crazy-max**

### CODE REVIEW

**Comment by crazy-max** [comment]
https://github.com/tonistiigi/xx/actions/runs/12200741186/job/34037574118?pr=174#step:5:783

```
 2.509 not ok 4 cross
2.510 # (in test file test-apk.bats, line 40)
2.512 #   `[ -f "/$(xx-info)/lib/libz.so.1" ]' failed
```

**Comment by crazy-max** [comment]
https://github.com/tonistiigi/xx/actions/runs/12201048147/job/34038587244#step:5:869

Looks like the arch has changes for i386:

```
 #85 55.68 # (from function `testHelloGO' in file test-go.bats, line 241,
#85 55.68 #  in test file test-go.bats, line 306)
#85 55.68 #   `testHelloGO' failed
#85 55.68 # file /tmp/a.out does not match expected target architecture 386: ELF 32-bit LSB executable, Intel i386, version 1 (SYSV), statically linked, Go BuildID=tlJHujLf8JLPAF5dYPfF/rijSNAaw8swSPvNg4IGt/4-GT7PqK9YJ69YYFBQrl/Hp7UJLaeCGcsmukHOQlY, with debug_info, not stripped
```

Expected `Intel 80386` but got `Intel i386`.

**Comment by crazy-max** [comment]
image

These ones are not related, should be fixed in another PR.

**Comment by tonistiigi** [comment]
> These ones are not related, should be fixed in another PR.

Agree, but we should fix that issue before merging this.

**Comment by tonistiigi** [comment]
should also add new cases to https://github.com/tonistiigi/xx/blob/master/src/test-verify.bats

**Review by tonistiigi — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
