### PR TITLE
github: add testing for debian:bookworm

### PR DESCRIPTION
**Pull request by tonistiigi**
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
Looks like `debian:sid` riscv port is currently broken. `gcc-10-base:amd64` and `gcc-10-base:riscv64` are conflicting and can't be installed at the same time. Hopefully this gets fixed in upstream.

**Comment by tonistiigi** [comment]
@crazy-max Is there some magic syntax that would make errors from `alpine:edge` and `debian:sid` non-fatal so CI runs to the end?

**Comment by crazy-max** [comment]
> 
> 
> @crazy-max Is there some magic syntax that would make errors from `alpine:edge` and `debian:sid` non-fatal so CI runs to the end?

Yes we can play with [`conclusion`/`outcome`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context). Just add a new field in the matrix like `allow-failure: <bool>` and in the step add `continue-on-error: ${{ matrix.allow-failure }}`. I think it should work.

**Comment by tonistiigi** [comment]
@crazy-max What's the difference with the last change?

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
